server:
  port: 8493

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/api-gateway?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

nginx:
  server_name: 127.0.0.1

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/config/mybatis-config.xml
